### ISSUE TITLE
database for student records

### ISSUE THREAD

**Issue by sashidhar-meesala** [HumberWinter2020/Humber-Media-Pros#19]
data for students has to be created in js object . please refer whatsapp group for referneces.

**Comment by ivandisantoso** [comment]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/55465401/76124772-725d3e00-5fc9-11ea-9cdc-b3de9012a83f.png">
I added an student array. You guys can add your information on the student array that I created

**Comment by sashidhar-meesala** [comment]
student data created
