### ISSUE TITLE
Work Breakdown - 1) Wireframing

### ISSUE THREAD

**Issue by sashidhar-meesala** [HumberWinter2020/Humber-Media-Pros#2]
Ivan will be working on the wire framing

**Comment by ivandisantoso** [comment]
Figma - Wire Frame
https://www.figma.com/file/SkDMKy0n4bs0YwPSiFIN5s/Humber-Media-Pros-Wire-Frame?node-id=4%3A17

**Comment by ivandisantoso** [comment]
1.1
Hi Team,
I've made a [wireframe](https://www.figma.com/file/SkDMKy0n4bs0YwPSiFIN5s/Humber-Media-Pros-Wire-Frame?node-id=29%3A4). Can you give me some idea about what should be added on the homepage and program page
