### ISSUE TITLE
student-profile css

### ISSUE THREAD

**Issue by louwx123** [HumberWinter2020/Humber-Media-Pros#20]

**Comment by ivandisantoso** [comment]
Hi Peter, I added some CSS on the student cards. You can add more to make nicer
[Screen Recording 2020-03-07 at 6.16.01 PM.zip](https://github.com/HumberWinter2020/Humber-Media-Pros/files/4302627/Screen.Recording.2020-03-07.at.6.16.01.PM.zip)

**Comment by louwx123** [comment]
done
